CREATE DATABASE IF NOT EXISTS mysns 
DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
USE mysns;

CREATE TABLE IF NOT EXISTS user (
    id BIGINT(16) UNSIGNED PRIMARY KEY,
    name VARCHAR(32),
    password CHAR(32),
    ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

